name = "BDF"
uuid = "4de61398-0c94-11ec-1711-35c2ab39c271"
authors = ["Robert Luke <mail@robertluke.net>"]
version = "1.0.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
